// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ExportPNG(arg1:string):Promise<string>;

export function ExportSVG(arg1:string):Promise<string>;

export function LoadFile():Promise<string>;

export function LoadFileByPath(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
