// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPNG(arg1) {
  return window['go']['files']['Service']['ExportPNG'](arg1);
}

export function ExportSVG(arg1) {
  return window['go']['files']['Service']['ExportSVG'](arg1);
}

export function LoadFile() {
  return window['go']['files']['Service']['LoadFile']();
}

export function SaveFile(arg1) {
  return window['go']['files']['Service']['SaveFile'](arg1);
}

export function Startup(arg1) {
  return window['go']['files']['Service']['Startup'](arg1);
}
