// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadPalettes() {
  return window['go']['config']['Service']['LoadPalettes']();
}

export function LoadPreferences() {
  return window['go']['config']['Service']['LoadPreferences']();
}

export function SavePalettes(arg1) {
  return window['go']['config']['Service']['SavePalettes'](arg1);
}

export function SavePreferences(arg1) {
  return window['go']['config']['Service']['SavePreferences'](arg1);
}

export function Startup(arg1) {
  return window['go']['config']['Service']['Startup'](arg1);
}
