// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';

export function LoadPalettes():Promise<string>;

export function LoadPreferences():Promise<config.Preferences>;

export function SavePalettes(arg1:string):Promise<void>;

export function SavePreferences(arg1:config.Preferences):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
