// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStartupFilePath():Promise<string>;

export function IsDarkTheme():Promise<boolean>;

export function SetStartupFilePath(arg1:string):Promise<void>;
