// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStartupFilePath() {
  return window['go']['app']['App']['GetStartupFilePath']();
}

export function IsDarkTheme() {
  return window['go']['app']['App']['IsDarkTheme']();
}

export function SetStartupFilePath(arg1) {
  return window['go']['app']['App']['SetStartupFilePath'](arg1);
}
