// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsDarkTheme() {
  return window['go']['app']['App']['IsDarkTheme']();
}
