// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Compile(arg1, arg2) {
  return window['go']['d2']['Service']['Compile'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['d2']['Service']['Startup'](arg1);
}
