// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPNG(arg1) {
  return window['go']['main']['App']['ExportPNG'](arg1);
}

export function ExportSVG(arg1) {
  return window['go']['main']['App']['ExportSVG'](arg1);
}

export function IsDarkTheme() {
  return window['go']['main']['App']['IsDarkTheme']();
}

export function LoadMermaid() {
  return window['go']['main']['App']['LoadMermaid']();
}

export function SaveMermaid(arg1) {
  return window['go']['main']['App']['SaveMermaid'](arg1);
}
