// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPNG(arg1:string):Promise<string>;

export function ExportSVG(arg1:string):Promise<string>;

export function IsDarkTheme():Promise<boolean>;

export function LoadMermaid():Promise<string>;

export function SaveMermaid(arg1:string):Promise<string>;
